; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

; -------------------------------------------------------------------------------------
;espidf-devkit-v1
; -------------------------------------------------------------------------------------
[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino

; -------------------------------------------------------------------------------------
;esp32-s3-fh4r2
; -------------------------------------------------------------------------------------
; [env:esp32-s3-fh4r2]
; platform = espressif32
; framework = arduino
; board = dfrobot_firebeetle2_esp32s3

; ; Memory Configuration for FH4R2 (4MB Flash QIO / 2MB PSRAM QSPI)
; board_upload.flash_size = 4MB
; board_build.flash_mode = qio
; board_build.psram_type = qio          
; board_build.arduino.memory_type = qio_qspi  ; REQUIRED: Maps the Arduino RAM allocation tables

; ; Partition Layout
; board_build.partitions = min_spiffs.csv ; huge_app.csv       ; Allocates max 3.12MB for your program sketch

; ; Compiler Flags
; build_flags = 
;     -DARDUINO_USB_CDC_ON_BOOT=1             ; Forces Serial.print out to native USB
;     -DBOARD_HAS_PSRAM                       ; Allocates memory allocation tables for external RAM

; -------------------------------------------------------------------------------------
; commons
; -------------------------------------------------------------------------------------

monitor_speed = 115200

lib_deps = 
	adafruit/Adafruit MPU6050 @ ^2.0.6
	adafruit/Adafruit PWM Servo Driver Library @ 3.0.3
	khoih-prog/ESP32_ISR_Servo @ 1.5.0
	wollewald/INA219_WE @ 1.4.1
	adafruit/Adafruit SSD1306 @ 2.5.13
	adafruit/Adafruit GFX Library @ 1.11.11

; --- OTA Upload Configuration ---
;upload_protocol = espota
;upload_port = 192.168.1.37 ; Replace with the actual IP address or use mDNS:
; upload_port = askalbot-rc.local